### PR TITLE
feat: added username validation

### LINKED ISSUE #22: [FEAT] :sparkles: Username should not contain any spaces or capital letters
### Description

When user will signup than the username should not contain any of these things

- Capital letters
- Numbers
- special characters
- spaces

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tharun634**
### Description

Validates username to find any invalid characters as per the regex.

### Checklist:

- [x] This pull request follow our contribution guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (postman and swagger)
- [x] I have written tests for the code
- [x] I have updated .env.example file for new .env variables

### What is current behavior?

Usernames are not being validated
Closes #22 

### What is new behavior?

Username's are now converted to lower case, trimmed and validated

image

### CODE REVIEW

**Review by aayushchugh — APPROVED** [review]
Nice work

**Comment by aayushchugh** [comment]
@tharun634 you can also join our discord server from here
https://discord.gg/kFJGJANZ

**Review by is-it-ayush — COMMENTED** [review]
Good! It'd also be great to add a email validation with all popular ending's in the same merge. So spamming is prohibited.

**Comment by aayushchugh** [comment]
@tharun634 can you refactor this code and use zod for validation there is file to that `/schemas/auth.schema`
https://zod.dev/?id=strings

**Comment by tharun634** [comment]
> Good! It'd also be great to add a email validation with all popular ending's in the same merge. So spamming is prohibited.

I believe Zod already takes care of that

https://github.com/MultiEmail/MultiEmail-backend/blob/f584c8786380f8f79da971d4995f46f603f0eb66/src/schemas/auth.schema.ts#L12

Unless you mean, to blacklist domains explicitly?

**Review by aayushchugh — COMMENTED** [review]
@tharun634 did you tested the code locally?

Everything else looks good

**Comment by is-it-ayush** [comment]
Instead of using this above Regex for username. Use this. Since when letting ```zod``` handle it. Zod only let's you proceed with checks if the verifcation is matched. In our case here, We want to discard the username and not proceed futher if it matches it. So I wote the inverse of the above regex. This. I have tested this one @tharun634 . Here ```/^[a-z\d0-9]+$/```. You can update it.

**Review by aayushchugh — APPROVED** [review]
Nice work @tharun634

**Review by is-it-ayush — APPROVED** [review]
Good Work @tharun634!

**Pull request merged**
